#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/acollign/colligno.helix-demo.xyz.git"

strains:
  - name: default
    code: https://github.com/acollign/colligno.helix-demo.xyz.git#master
    content: https://github.com/acollign/colligno.helix-demo.xyz.git#master
    static: https://github.com/acollign/colligno.helix-demo.xyz.git/htdocs#master
    package: colligno/3e90491120fbbbf6f99bc89d94b6df4a147f7677
